apiVersion: v1
kind: PersistentVolume
metadata:
  name: aws-pv-mysql
  labels:
    type: aws-pv-mysql
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-05467f85f3d7e8db8
    fsType: xfs
