apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQLROOTPASSWORD: ZWNobyAtbiBwYXNzd29yZDEyMwo=
  MYSQLDATABASE: ZWNobyAtbiBkYgo=
  MYSQLUSER: ZWNobyAtbiBwcmFuYXYK
  MYSQLPASSWORD: ZWNobyAtbiBhZG1pbkAxMjMK
