apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-mysql
  labels: 
    app: wordpress
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: wordpress  
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      volumes:
        - name: aws-pv-mysql
          persistentVolumeClaim:
            claimName: task-pv-claim     
      containers:
      - image: mysql:latest
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysqlrootpassword
        - name: MYSQL_USER
          value: pranav
        - name: MYSQL_DATABASE
          value: db
        - name: MYSQL_PASSWORD
          value: admin@123  
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: aws-pv-mysql
          mountPath: /var/lib/mysql
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
spec:
  ports:
    - port: 3306
  selector: 
    app: wordpress
  clusterIP: None

